---
title: "Introduction to Machine Learning"
subtitle: "Lab 1"
author: "Rasmus Holm"
date: "`r Sys.Date()`"
fontsize: 10pt
geometry: margin=1in
output:
    pdf_document:
        toc: true
        number_sections: false
        fig_caption: yes
        keep_tex: yes
        includes:
            in_header: styles.sty
---

```{r global-options, echo = FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
knitr::opts_chunk$set(fig.pos='H', fig.align='center')

knitr::read_chunk("../assignment1/solution.R")
knitr::read_chunk("../assignment2/solution.R")
```

\newpage

\section{Assignment 1}
```{r, echo=FALSE, eval=TRUE}
<<assign1-init>>
```

## 2.3
```{r, echo=FALSE, eval=TRUE}
<<assign1-3-table>>
```

## 2.4
```{r, echo=FALSE, eval=TRUE}
<<assign1-4-table>>
```

## 2.5
```{r, echo=FALSE, eval=TRUE}
<<assign1-5-table>>
```

## 2.6
```{r, echo=FALSE, eval=TRUE}
<<assign1-6-init>>
```

```{r ROC, echo=FALSE, fig.cap="Receiver operating characteristic curves."}
<<assign1-6-ROC>>
```

\newpage

\section{Assignment 2}

```{r, echo=FALSE, eval=TRUE}
<<assign2-init>>
```

## 2.2
```{r, echo=FALSE, eval=TRUE}
<<assign2-2-init>>
```

```{r distribution, echo=FALSE, fig.cap="Data Distribution."}
<<assign2-2-plot-distribution>>
```

```{r likelihood2, echo=FALSE, fig.cap="Likelihoods."}
<<assign2-2-plot-likelihoods>>
```

## 2.3
```{r, echo=FALSE, eval=TRUE}
<<assign2-3-init>>
```

```{r likelihood3, echo=FALSE, fig.cap="Likelihoods."}
<<assign2-3-plot-likelihoods>>
```

```{r likelihood36, echo=FALSE, fig.cap="Likelihoods."}
<<assign2-3-plot-likelihoods-6>>
```

## 2.4
```{r, echo=FALSE, eval=TRUE}
<<assign2-4-init>>
```

```{r posterior, echo=FALSE, fig.cap="Likelihoods."}
<<assign2-4-plot-posteriors>>
```

## 2.5
```{r, echo=FALSE, eval=TRUE}
<<assign2-5-init>>
```

```{r distribution5, echo=FALSE, fig.cap="Likelihoods."}
<<assign2-5-plot-distribution>>
```
