---
title: "Introduction to Machine Learning"
subtitle: "Lab 2 Block 2"
author: "Rasmus Holm"
date: "`r Sys.Date()`"
fontsize: 10pt
geometry: margin=1in
output:
    pdf_document:
        toc: true
        number_sections: false
        fig_caption: yes
        keep_tex: yes
        includes:
            in_header: styles.sty
---

```{r global-options, echo = FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
knitr::opts_chunk$set(fig.pos='H', fig.align='center')

knitr::read_chunk("../assignment1a/solution.R")
knitr::read_chunk("../assignment2a/solution.R")
knitr::read_chunk("../assignment3a/solution.R")
knitr::read_chunk("../assignment4a/solution.R")

knitr::read_chunk("../assignment1b/solution.R")
knitr::read_chunk("../assignment2b/solution.R")
```

\newpage

# Assignment 1a
```{r, echo=FALSE, eval=TRUE}
<<assign1a-init>>
```

\newpage

# Assignment 1b
```{r, echo=FALSE, eval=TRUE}
<<assign1b-init>>
```

\newpage

# Assignment 2a
```{r, echo=FALSE, eval=TRUE}
<<assign2a-init>>
```

## 1

## 2

## 3

\newpage

# Assignment 2b
```{r, echo=FALSE, eval=TRUE}
<<assign2b-init>>
```

\newpage

# Assignment 3a
```{r, echo=FALSE, eval=TRUE}
<<assign3a-init>>
```

## 1

## 2

\newpage

# Assignment 4a
```{r, echo=FALSE, eval=TRUE}
<<assign4a-init>>
```

```{r, echo=FALSE, eval=TRUE}
<<assign4a-tree>>
```

```{r, echo=FALSE, eval=TRUE}
<<assign4a-tree-plot>>
```

```{r, echo=FALSE, eval=TRUE}
<<assign4a-forest>>
```

```{r, echo=FALSE, eval=TRUE}
<<assign4a-forest-plot>>
```

\newpage

# Appendix

## Code for Assignment 1a
```{r, echo=TRUE, eval=FALSE, tidy=FALSE, highlight=TRUE}
```

## Code for Assignment 1b
```{r, echo=TRUE, eval=FALSE, tidy=FALSE, highlight=TRUE}
```

## Code for Assignment 2a
```{r, echo=TRUE, eval=FALSE, tidy=FALSE, highlight=TRUE}
```

## Code for Assignment 2b
```{r, echo=TRUE, eval=FALSE, tidy=FALSE, highlight=TRUE}
```

## Code for Assignment 3a
```{r, echo=TRUE, eval=FALSE, tidy=FALSE, highlight=TRUE}
```

## Code for Assignment 4a
```{r, echo=TRUE, eval=FALSE, tidy=FALSE, highlight=TRUE}
<<assign4a-init>>
<<assign4a-tree>>
<<assign4a-tree-plot>>
<<assign4a-forest>>
<<assign4a-forest-plot>>
```
