---
title: "Introduction to Machine Learning"
subtitle: "Lab 3 Block 2"
author: "Rasmus Holm"
date: "`r Sys.Date()`"
fontsize: 10pt
geometry: margin=1in
output:
    pdf_document:
        toc: true
        number_sections: false
        fig_caption: yes
        keep_tex: yes
        includes:
            in_header: styles.sty
---

```{r global-options, echo = FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
knitr::opts_chunk$set(fig.pos='H', fig.align='center')

knitr::read_chunk("../assignment1/solution.R")
knitr::read_chunk("../assignment2/solution.R")
```

\newpage

# Assignment 1
```{r, echo=FALSE, eval=TRUE}
<<assign1-init>>
```

## 1
```{r, echo=FALSE, eval=TRUE, results="hide"}
<<assign1-1-nsc>>
```

```{r, echo=FALSE, eval=TRUE}
<<assign1-1-nsc-result>>
```

```{r, echo=FALSE, eval=TRUE}
<<assign1-1-nsc-plot>>
```

## 2
### Elastic Net
```{r, echo=FALSE, eval=TRUE}
<<assign1-2-elasticnet>>
```

```{r, echo=FALSE, eval=TRUE}
<<assign1-2-elasticnet-result>>
```


### Support Vector Machine
```{r, echo=FALSE, eval=TRUE, results="hide"}
<<assign1-2-svm>>
```

```{r, echo=FALSE, eval=TRUE}
<<assign1-2-svm-result>>
```

## 3
```{r, echo=FALSE, eval=TRUE}
<<assign1-3-benjhoch>>
```

```{r, echo=FALSE, eval=TRUE}
<<assign1-3-features>>
```

```{r, echo=FALSE, eval=TRUE}
<<assign1-3-plot>>
```

\newpage

# Assignment 2
```{r, echo=FALSE, eval=TRUE}
<<assign2-init>>
```

\newpage

# Appendix
## Code for Assignment 1
```{r, echo=TRUE, eval=FALSE, tidy=FALSE, highlight=TRUE}
<<assign1-init>>

<<assign1-1-nsc>>
<<assign1-1-nsc-result>>
<<assign1-1-nsc-plot>>

<<assign1-2-elasticnet>>
<<assign1-2-elasticnet-result>>

<<assign1-2-svm>>
<<assign1-2-svm-result>>

<<assign1-3-benjhoch>>
<<assign1-3-features>>
<<assign1-3-plot>>
```

## Code for Assignment 2
```{r, echo=TRUE, eval=FALSE, tidy=FALSE, highlight=TRUE}
<<assign2-init>>
```
